<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<Copyright>Copyright © const.me, 2019-2025</Copyright>
		<RepositoryUrl>https://github.com/Const-me/ComLightInterop</RepositoryUrl>
		<Company>const.me</Company>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DefineConstants>$(DefineConstants);OFFLINE_CODEGEN</DefineConstants>
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<LangVersion>latest</LangVersion>
		<AssemblyName>ComLight</AssemblyName>
		<RootNamespace>ComLight</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\ComLight\AssemblyInfo.cs" Link="AssemblyInfo.cs" />
	  <Compile Include="..\ComLight\ComInterfaceAttribute.cs" Link="ComInterfaceAttribute.cs" />
	  <Compile Include="..\ComLight\CustomConventionsAttribute.aot.cs" Link="CustomConventionsAttribute.aot.cs" />
	  <Compile Include="..\ComLight\DebuggerTypeProxyAttribute.cs" Link="DebuggerTypeProxyAttribute.cs" />
	  <Compile Include="..\ComLight\iComDisposable.cs" Link="iComDisposable.cs" />
	  <Compile Include="..\ComLight\IO\iReadStream.cs" Link="IO\iReadStream.cs" />
	  <Compile Include="..\ComLight\IO\iWriteStream.cs" Link="IO\iWriteStream.cs" />
	  <Compile Include="..\ComLight\IUnknown.cs" Link="IUnknown.cs" />
	  <Compile Include="..\ComLight\ManagedObject.cs" Link="ManagedObject.cs" />
	  <Compile Include="..\ComLight\ManagedWrapper.aot.cs" Link="ManagedWrapper.aot.cs" />
	  <Compile Include="..\ComLight\ManagedWrapper.cache.cs" Link="ManagedWrapper.cache.cs" />
	  <Compile Include="..\ComLight\MarshallerAttribute.aot.cs" Link="MarshallerAttribute.aot.cs" />
	  <Compile Include="..\ComLight\RetValIndexAttribute.cs" Link="RetValIndexAttribute.cs" />
	  <Compile Include="..\ComLight\RuntimeClass.cs" Link="RuntimeClass.cs" />
	  <Compile Include="..\ComLight\Utils\ErrorCodes.cs" Link="Utils\ErrorCodes.cs" />
	  <Compile Include="..\ComLight\Utils\errorCodez.cs" Link="Utils\errorCodez.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Utils\" />
	</ItemGroup>

</Project>