using System.Collections.Generic;

namespace ComLight
{
	// This part of the class is automatically generated by a T4 template, by parsing C headers in ComLightLib and in Windows SDK
	public static partial class ErrorCodes
	{
		static readonly Dictionary<int, string> codes = new Dictionary<int, string>()
		{
			{ unchecked( (int)0x80040007 ), "Uninitialized object" },  // OLE_E_BLANK
			{ unchecked( (int)0x8000000B ), "The operation attempted to access data outside the valid range" },  // E_BOUNDS
			{ unchecked( (int)0x80070026 ), "Attempted to read past the end of the stream" },  // E_EOF
			{ unchecked( (int)0x800704DF ), "An attempt was made to perform an initialization operation when initialization has already been completed" },  // E_ALREADY_INITIALIZED
		};
	}
}